
name: Run Tests

on:
  push:
    branches:
      - '*'
  pull_request:

jobs:
  test:
    runs-on: windows-latest
    name: Perl windows with dist choco
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - run: perl -MGD -le "say $GD::Version"
      - name: Set up LibGD
        run: pacman -S --needed --noconfirm mingw-w64-x86_64-libgd
      - run: perl -V
      - name: Install Perl deps
        run: |
          cpanm --notest -v Archive::Zip
