
name: Run Tests

on:
  push:
    branches:
      - '*'
  pull_request:

jobs:
  test:
    env:
      PERL_USE_UNSAFE_INC: 0
      AUTHOR_TESTING: 0
      AUTOMATED_TESTING: 1
      RELEASE_TESTING: 0
      VCPKG_DEFAULT_TRIPLET: x64-windows
    runs-on: windows-latest
    name: Perl windows
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - run: perl -V
      - name: install cpan deps
        uses: perl-actions/install-with-cpm@v1.7
        with:
          install: |
            GD
            Archive::Zip
            Config::Tiny
      - name: install cpan deps
        uses: perl-actions/install-with-cpanm@v1.5
        with:
          install: |
            Geo::ShapeFile
      - run: echo "C:\strawberry\c\bin;C:\strawberry\perl\site\bin;C:\strawberry\perl\bin" >> $GITHUB_PATH
      - run: pp -o pullauta.exe -M GD -M POSIX -M Config::Tiny -M Geo::ShapeFile -M Archive::Zip --link libbz2-1__.dll -l libfreetype-6__.dll -l libgd-3__.dll -l libiconv-2__.dll -l libjpeg-9__.dll -l liblzma-5__.dll -l libpng16-16__.dll -l libtiff-5__.dll -l libXpm__.dll -l zlib1__.dll pullauta.pl
