
name: Run Tests

on:
  push:
    branches:
      - '*'
  pull_request:

jobs:
  test:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    name: Perl windows with dist msys2
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up MSYS2
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            base-devel
            mingw-w64-x86_64-toolchain
            mingw-w64-x86_64-perl
      - name: Set up LibGD
        run: pacman -S --needed --noconfirm mingw-w64-x86_64-libgd
      - run: perl -V
      - name: Install cpanm
        run:
          yes | cpan -T App::cpanminus || true
      - name: Install Perl deps
        run: |
          cpanm --notest PAR::Packer GD POSIX Config::Tiny Geo::ShapeFile Archive::Zip
