
name: Run Tests

on:
  push:
    branches:
      - '*'
  pull_request:

jobs:
  test:
    env:
      PERL_USE_UNSAFE_INC: 0
      AUTHOR_TESTING: 0
      AUTOMATED_TESTING: 1
      RELEASE_TESTING: 0
      VCPKG_DEFAULT_TRIPLET: x64-windows
    runs-on: windows-latest
    name: Perl windows
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - run: perl -V
      - name: install cpan deps
        uses: perl-actions/install-with-cpm@v1.3
        with:
          install: |
            GD
      - run: echo "C:\strawberry\c\bin;C:\strawberry\perl\site\bin;C:\strawberry\perl\bin" >> $GITHUB_PATH
      - run: perl -MGD -e1
