name: Run Tests

on:
  push:
    branches:
      - '*'
  pull_request:

jobs:
  test:
    runs-on: windows-latest
    name: Create executable for windows
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Perl
        run: |
          choco upgrade strawberryperl
          echo "C:\strawberry\c\bin;C:\strawberry\perl\site\bin;C:\strawberry\perl\bin" >> $GITHUB_PATH
      - name: perl -V
        run: perl -V
      - name: install cpanm and multiple modules
        uses: perl-actions/install-with-cpanm@stable
        with:
          install: |
            POSIX
            GD
            Config::Tiny
            Geo::ShapeFile
            Archive::Zip
            PAR::Packer
